#format is target-name: target dependencies
#{-tab-}actions

# All Targets
all: task1

# Tool invocations
# Executable "hello" depends on the files hello.o and run.o.
task1: task1.o asm_task1.o
	gcc -m32 -g -Wall -o task1 task1.o asm_task1.o

# Depends on the source and header files
task1.o: main_task1Assignment1.c 
	gcc -g -Wall -m32 -ansi -c -o task1.o main_task1Assignment1.c 
 
asm_task1.o: asm_task1Assignment1.s
	nasm -g -f elf -w+all -o asm_task1.o asm_task1Assignment1.s


#tell make that "clean" is not a file name!
.PHONY: clean

#Clean the build directory
clean: 
	rm -f *.o task1
